name: Deploy Face Recognition AI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Create Deployment Artifact
        # Kita bungkus semua file kecuali venv, git, dan env lokal
        run: |
          tar -czf /tmp/app.tar.gz --exclude='.git' --exclude='.github' --exclude='venv' --exclude='.env' .
          
          # Pindahkan kembali ke folder project agar bisa di-upload sebagai artifact
          mv /tmp/app.tar.gz .
          
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-python
          path: app.tar.gz

  deploy:
    name: Deploy to Production
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: app-python

      - name: Install ssh key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add host to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -T 10 -p "${{ secrets.SSH_PORT }}" "${{ secrets.SSH_HOST }}" >> ~/.ssh/known_hosts

      - name: Deploy Process
        run: |
          # Variabel di GitHub Runner
          REL=$(date +%Y%m%d%H%M%S)-${GITHUB_SHA::7}
          APP_DIR="/var/www/face_recognition"
          
          scp -O -o StrictHostKeyChecking=no -P "${{ secrets.SSH_PORT }}" app.tar.gz ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:$APP_DIR/releases/tmp-$REL.tar.gz

          ssh -tt -o StrictHostKeyChecking=no -p "${{ secrets.SSH_PORT }}" ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
            set -e
            
            # Oper variabel ke shell VPS
            REL=$REL
            APP_DIR=$APP_DIR
            
            # Gunakan \$ untuk semua variabel agar dibaca di VPS
            cd \$APP_DIR/releases
            
            # Ekstrak rilis baru
            mkdir -p \$REL
            tar -xzf tmp-\$REL.tar.gz -C \$REL
            rm tmp-\$REL.tar.gz
            cd \$REL
            
            # --- LINKING SHARED RESOURCES ---
            mkdir -p \$APP_DIR/shared/uploads
            
            ln -sfn \$APP_DIR/shared/.env .env
            ln -sfn \$APP_DIR/shared/uploads uploads

            # --- FIX PERMISSIONS ---
            sudo chown -R www-data:www-data .
            sudo chown -R www-data:www-data \$APP_DIR/shared/uploads
            sudo chmod -R 775 \$APP_DIR/shared/uploads
            
            # --- DEPENDENCIES ---
            \$APP_DIR/shared/venv/bin/pip install --upgrade pip
            \$APP_DIR/shared/venv/bin/pip install -r requirements.txt

            # --- AKTIVASI ---
            ln -sfn \$APP_DIR/releases/\$REL \$APP_DIR/current
            
            # --- RELOAD SERVICE ---
            echo 'Restarting Python Service...'
            sudo systemctl restart face_recognition
            echo 'Deployment Successful!'
          "